export const COURSE_REGISTER_REQUEST = 'COURSE_REGISTER_REQUEST'
export const COURSE_REGISTER_SUCCESS = 'COURSE_REGISTER_SUCCESS' 
export const COURSE_REGISTER_FAIL    = 'COURSE_REGISTER_FAIL' 

export const COURSE_LOGIN_REQUEST = 'COURSE_LOGIN_REQUEST'
export const COURSE_LOGIN_SUCCESS = 'COURSE_LOGIN_SUCCESS'
export const COURSE_LOGIN_FAIL    = 'COURSE_LOGIN_FAIL'

export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST'
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS' 
export const COURSE_LIST_FAIL =    'COURSE_LIST_FAIL'

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST'
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS' 
export const COURSE_DETAILS_FAIL =    'COURSE_DETAILS_FAIL'



export const COURSE_PDF_REQUEST = 'COURSE_PDF_REQUEST'
export const COURSE_PDF_SUCCESS = 'COURSE_PDF_SUCCESS' 
export const COURSE_PDF_FAIL =    'COURSE_PDF_FAIL'
