export const SESSION_REGISTER_REQUEST = 'SESSION_REGISTER_REQUEST'
export const SESSION_REGISTER_SUCCESS = 'SESSION_REGISTER_SUCCESS' 
export const SESSION_REGISTER_FAIL = 'SESSION_REGISTER_FAIL' 

export const SESSION_LOGIN_REQUEST = 'SESSION_LOGIN_REQUEST'
export const SESSION_LOGIN_SUCCESS = 'SESSION_LOGIN_SUCCESS'
export const SESSION_LOGIN_FAIL = 'SESSION_LOGIN_FAIL'

export const SESSION_LIST_REQUEST = 'SESSION_LIST_REQUEST'
export const SESSION_LIST_SUCCESS = 'SESSION_LIST_SUCCESS'  
export const SESSION_LIST_FAIL = 'SESSION_LIST_FAIL'


export const SESSION_UPDATE_LIST_REQUEST = 'SESSION_UPDATE_LIST_REQUEST'
export const SESSION_UPDATE_LIST_SUCCESS = 'SESSION_UPDATE_LIST_SUCCESS' 
export const SESSION_UPDATE_LIST_FAIL =    'SESSION_UPDATE_LIST_FAIL'

 

export const SESSION_DETAILS_REQUEST = 'SESSION_DETAILS_REQUEST'
export const SESSION_DETAILS_SUCCESS = 'SESSION_DETAILS_SUCCESS' 
export const SESSION_DETAILS_FAIL =    'SESSION_DETAILS_FAIL' 
